name: Snyk Scan

on: [push, pull_request_target]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo to access secrets
        uses: actions/checkout@v3
      - name: Chekcout the code from the forked branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Test for open source vulnerabilities and license issues.
        uses: snyk/actions/python-3.9@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects
      - name: Test for any known security issues using Static Code Analysis.
        uses: snyk/actions/python-3.9@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --all-projects
